services:
  # postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: evennt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  # Para visualizar o database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

  # API KTOR Server
  api-ktor-server:
    container_name: api-ktor-server
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pg_data: