name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  # MARK: Publish Ktor Server
  publish-ktor-server:
    name: Publish Ktor Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push api-producer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monitoring-system-ktor-server:latest
  # MARK: Deploy to K8s
  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs:
      - publish-ktor-server
    env:
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
      JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
      JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
      JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
      JWT_REALM: ${{ secrets.JWT_REALM }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DRIVER: ${{ secrets.DB_DRIVER }}
    steps:
      - uses: actions/checkout@v3

      - name: Criar namespace
        run: |
          kubectl apply -f k8s/namespace.yaml
      
      - name: Criar o secret
        run: |
          chmod +x ./k8s/deploy.sh
          ./k8s/deploy.sh

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/monitoring-system.yaml